Update API examples to Workflow Package 1.4.2
gematik/eRezept-Examples pull request #61
Opened 2024-09-17 14:32 UTC by Hendrejvr

The API examples are updated to make use of the Workflow Package 1.4.2

2024-09-19 09:48 UTC, florianschoffke requested changes
Ich kriege in den folgenden Dateien noch Fehler:
Bundle-erp-chargeltem-05-GET-Chargeltem-Response.json
Bundle-erp-chargeltem-09-GET-Chargeltem-Response.json
Bundle-erp-communication-08-response-GetAllMessages.json
Bundle-erp-consent-03-response-GetConsent.json
Bundle-erp-diga-02-response-fhir-vzd.json
Bundle-erp-versicherte-02-response-taskGetSingle.json
Bundle-erp-versicherte-03-response-GetLocation.json
Consent-erp-consent-01-request-PostConsent.json
Consent-erp-consent-02-response-PostConsent.json
Parameters-erp-abrufen-06-request-taskClose.json
Parameters-erp-abrufen-07-request-taskCloseMultiple.json
Parameters-erp-abrufen-08-response-taskDispense.json
Parameters-erp-eml-epa-notes-01-Parameters-ExampleCloselnputParameters.json
Parameters-erp-eml-epa-notes-02-Parameters-ExampleInputMultipleDispenses.json

Können die behoben werden? 
Wahrscheinlich auch noch Überreste vom vorherigen PR, wo es nicht ganz sauber war. Wir sollten FSH und HAPI nutzen um vollständig valide Beispiele zu haben.

Abgekürzte Beispiele sollten wir mit FSH auch zu kompletten Beispielen machen. In der API können wir über "einklappen" das optisch besser darstellen.

2024-10-18 07:40 UTC, Hendrejvr commented
@florianschoffke Bitte beim reviewen auf die Tasks, ChargeItems und MedicationDispenses achten

2024-10-24 13:47 UTC, florianschoffke approved these changes

2024-11-06 07:05 UTC, florianschoffke approved these changes

2024-11-06 07:07 UTC, merged