Update the erp_eml-epa-notes examples
gematik/eRezept-Examples pull request #64
Opened 2024-10-11 13:21 UTC by Hendrejvr

Update the examples that are used on the erp_eml-epa-notes page

2024-10-14 04:14 UTC, florianschoffke commented
Bin nicht ganz sicher, ob das korrekt ist. Die Beispiele sind im Ordner 2024-11-01, aber die Profilnummern sind auf 1.4. Das sollte doch erst ab 2025-01-15 der Fall sein oder?

2024-10-14 06:46 UTC, Hendrejvr commented
Du hast recht. Das Examples-Repo ist nicht aus Sicht des Api-Docs-Repos, sondern unabhängig davon

2024-10-14 10:27 UTC, florianschoffke requested changes

2024-10-14 10:27 UTC, florianschoffke commented on API-Examples/2025-01-15/erp_eml-epa-notes/01_Parameters-ExampleCloseInputParameters.xml
> +					<extension url="https://gematik.de/fhir/dev-epa-medication/StructureDefinition/drug-category-extension">
das hier sollte aber nicht mit 'dev-' anfangen

2024-10-14 10:27 UTC, florianschoffke commented on API-Examples/2025-01-15/erp_eml-epa-notes/01_Parameters-ExampleCloseInputParameters.xml
> +					<extension url="https://gematik.de/fhir/dev-epa-medication/StructureDefinition/drug-category-extension">
Für 1.3 gibt es ja noch keine GEM_ERP_PR_Medication. Also 1.4 sollte schon da stehen

2024-10-14 11:53 UTC, Hendrejvr commented on API-Examples/2025-01-15/erp_eml-epa-notes/01_Parameters-ExampleCloseInputParameters.xml
> +					<extension url="https://gematik.de/fhir/dev-epa-medication/StructureDefinition/drug-category-extension">
Stimmt. Das habe ich im anderen PR gemacht. Jetzt habe ich es auch hier getan.

2024-10-15 07:06 UTC, florianschoffke approved these changes
approved

2024-10-15 07:08 UTC, merged